CREATE TABLE `ADMIN_USER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `LOGIN_NAME` varchar(45) COLLATE utf8_bin NOT NULL,
  `PASSWORD` varchar(45) COLLATE utf8_bin NOT NULL,
  `LOGIN_COUNT` int(11) DEFAULT NULL,
  `STATUS` varchar(45) COLLATE utf8_bin DEFAULT NULL,
  `CREATE_TIME` timestamp NULL DEFAULT NULL,
  `LAST_LOGIN_TIME` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ID`,`LOGIN_NAME`,`PASSWORD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;