CREATE TABLE `TREE_MENU` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TEXT` varchar(45) COLLATE utf8_bin NOT NULL,
  `PARENT_ID` int(11) NOT NULL,
  `STATUS` char(1) COLLATE utf8_bin NOT NULL DEFAULT 'Y' COMMENT '菜单是否全局可见 Y/N',
  `URL` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `ORDER` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
